name: Publish NPM

on:
  push:
    branches:
      - 'v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+'

############
# Set Jobs #
############
jobs:
  ##############
  # Define Job #
  ##############
  publish-npm:
    name: Publish NPM
    uses: cart180/Reusable-Workflows/.github/workflows/publish-npm.yml@main
    with:
      dist: publish_esm
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
