name: Vet Code

on:
  push:
    branches-ignore:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
    paths:
      - 'src/**'
      - 'snowpack.config.js'
      - 'package.json'
      - .github/workflows/vet-code.yml

############
# Set Jobs #
############
jobs:
  ##############
  # Define Job #
  ##############
  vet-code:
    name: Vet Code
    uses: cart180/Reusable-Workflows/.github/workflows/vet-node-code.yml@main
